/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkUpdatesRouteImport } from './routes/work-updates'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAdminInviteRouteImport } from './routes/api/admin/invite'

const WorkUpdatesRoute = WorkUpdatesRouteImport.update({
  id: '/work-updates',
  path: '/work-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInviteRoute = ApiAdminInviteRouteImport.update({
  id: '/api/admin/invite',
  path: '/api/admin/invite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/work-updates': typeof WorkUpdatesRoute
  '/api/admin/invite': typeof ApiAdminInviteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/work-updates': typeof WorkUpdatesRoute
  '/api/admin/invite': typeof ApiAdminInviteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/work-updates': typeof WorkUpdatesRoute
  '/api/admin/invite': typeof ApiAdminInviteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expenses'
    | '/login'
    | '/set-password'
    | '/work-updates'
    | '/api/admin/invite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expenses'
    | '/login'
    | '/set-password'
    | '/work-updates'
    | '/api/admin/invite'
  id:
    | '__root__'
    | '/'
    | '/expenses'
    | '/login'
    | '/set-password'
    | '/work-updates'
    | '/api/admin/invite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpensesRoute: typeof ExpensesRoute
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  WorkUpdatesRoute: typeof WorkUpdatesRoute
  ApiAdminInviteRoute: typeof ApiAdminInviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-updates': {
      id: '/work-updates'
      path: '/work-updates'
      fullPath: '/work-updates'
      preLoaderRoute: typeof WorkUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/invite': {
      id: '/api/admin/invite'
      path: '/api/admin/invite'
      fullPath: '/api/admin/invite'
      preLoaderRoute: typeof ApiAdminInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpensesRoute: ExpensesRoute,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  WorkUpdatesRoute: WorkUpdatesRoute,
  ApiAdminInviteRoute: ApiAdminInviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
