
ALTER TABLE public.fund_expenses
  ADD COLUMN IF NOT EXISTS fy23 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fy26 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fy27 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fy28 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fy29 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fy30 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fy31 numeric NOT NULL DEFAULT 0;

ALTER TABLE public.im_expenses
  ADD COLUMN IF NOT EXISTS fy23 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fy26 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fy27 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fy28 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fy29 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fy30 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fy31 numeric NOT NULL DEFAULT 0;
